export const constants = {
    SET_LOADED: 'SET_LOADED',
    SET_ITEMS: 'SET_ITEMS',
    SET_SORT_BY: 'SET_SORT_BY',
    SET_CATEGORY: 'SET_CATEGORY',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    CLEAR_CART: 'CLEAR_CART',
    REMOVE_CART_ITEM: 'REMOVE_CART_ITEM',
    PLUS_CART_ITEM: 'PLUS_CART_ITEM',
    MINUS_CART_ITEM: 'MINUS_CART_ITEM'
}